### ISSUE TITLE
Fleiri kjörtímabil

### ISSUE THREAD

**Issue by viktorsmari** [baering/thingmenn#23]
Verður mögulegt að geta valið síðustu kjörtímabil?

Og mögulega sjá núverandi kjörtímabil, sem væri kannski uppfært/skrapað á einhverra mán fresti eða álíka?

**Comment by baering** [comment]
Sæll Viktor, afsakaðu **hrikalega** lélegan svartíma. Gögn fyrir síðustu 10 ár eru nú komin inn! Sjáum svo hvað setur með automatic scraping.
