### ISSUE TITLE
frontend should start with current year

### ISSUE THREAD

**Issue by herrhelms** [baering/thingmenn#27]
congrats on shipping v2 - I suppose it would be good to start the page with http://www.thingmenn.is/thing/147 instead of `/thing/allt`

**Comment by baering** [comment]
💯 

Took 4 years, but this [is done](https://github.com/baering/thingmenn/commit/570ad3e9c2a028868bb9e43a9cdcf21a175ff76f#diff-ffc4b3ed043acab1dfe225972154854fc5f02a11179919447592564dd611198cR43) 😆
